/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "noTranslations": true,
  "name": "Online Collaboration",
  "description": "Adds online collaboration features to the editor.",
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "dynamicDisable": true,
  "tags": [
    "new"
  ],
  "enabledByDefault": true
};
export default manifest;
