/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "noTranslations": true,
  "name": "Online Collaboration",
  "description": "Adds online collaboration features to the editor.",
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "settings": [
    {
      "id": "disableBlackbox",
      "name": "Disable Flight Recorder",
      "type": "boolean",
      "default": false
    }
  ],
  "info": [
    {
      "text": "WARNING: Disabling the Flight Recorder will make it impossible for developers to debug issues or desyncs you encounter.",
      "type": "warning",
      "id": "blackboxWarning"
    }
  ],
  "dynamicDisable": true,
  "tags": [
    "new"
  ],
  "enabledByDefault": true
};
export default manifest;
